// Code generated by MCHP Chatbot
/*
� [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#include "hal.h"
#include "systick/systick.h"
#include "T1S/t1s_lwip.h"
#include "T1S/udp_perf_client.h"
#include "X2Cscope/X2Cscope.h"
#include "app.h"
#include "userparms.h"

#include <stdio.h>

/*
    Main application
*/

/* Sector : 1CA 2CB 3AB 4AC 5BC 6BA - CA means switches CH and AL*/
const uint32_t PWM_STATE1[8] = {0x00300000, 0x00301000, 0x00300000, 0x00100000, 0x00100000, 0x00300000, 0x00301000, 0x00300000};
const uint32_t PWM_STATE2[8] = {0x00300000, 0x00300000, 0x00301000, 0x00301000, 0x00300000, 0x00100000, 0x00100000, 0x00300000};
const uint32_t PWM_STATE3[8] = {0x00300000, 0x00100000, 0x00100000, 0x00300000, 0x00301000, 0x00301000, 0x00300000, 0x00300000};

#ifdef HURST300
    /* Forward Hall Sequence ABC : 5-4-6-2-3-1 with sectors 6BA-1CA-2CB-3AB-4AC-5BC */
    const uint16_t CommutationSector[8] = {0, 5, 3, 4, 1, 6, 2, 0}; 
#endif
#ifdef ACT57BLF02
    /* Forward Hall Sequence ABC : 5-4-6-2-3-1 with sectors 3AB-4AC-5BC-6BA-1CA-2CB */
    const uint16_t CommutationSector[8] = {0, 2, 6, 1, 4, 3, 5, 0}; 
#endif
#ifdef ACT57BLF02_EC1024_500_T
    /* Reverse Hall Sequence ABC : 5-4-6-2-3-1 with sectors 1CA-2CB-3AB-4AC-5BC-6BA */
    const uint16_t CommutationSector[8] = {0, 6, 4, 5, 2, 1, 3, 0};
#endif

uint16_t RunMotorCommand = 0;
uint16_t motorDirection = 0;
uint16_t HallValue;

uint32_t PotValue;
float    Ia, Ib, Ic, Ibus;
float    Va, Vb, Vc, Vbus;
uint32_t DesiredPWMDutyCycle;
uint32_t CurrentPWMDutyCycle;
uint32_t dutyRampValue = 200;

uint16_t heartBeatCount = 0;
#define HEART_BEAT_LED_COUNT_mS 250

/* Function Prototypes */
void PWM_setState(uint16_t sector);

/*
 * 
 */
int main()
{
    HAL_Init();
    PWM_setState(0);
    SysTick_Initialize();
    APP_Buttons_Init();

    printf("dsPIC33AK512MC510 + HallSensor + T1S\r\n");

    T1S_init();
    X2Cscope_Init();

    SYSTICK_TIMEOUT led_timeout;
    SysTick_StartTimeOut(&led_timeout, HEART_BEAT_LED_COUNT_mS);
    
    while(1)
    {
        X2Cscope_Communicate();
        T1S_execute();
        APP_Buttons_Task();

        if (APP_Button_WasPressed(APP_BTN_SW1))
        {
            if(RunMotorCommand == 0)
            {
                if(PotValue < ((uint16_t)(MAX_ADC_COUNT)) >> 2)
                {
                    RunMotorCommand = 1;
                }
            }
            else if(RunMotorCommand == 1)
            {
                RunMotorCommand = 0;
            }
        }
        
        RunMotorCommand == 1 ? LED2_SetHigh() : LED2_SetLow();
        
        if (APP_Button_WasPressed(APP_BTN_SW2))
        {
            /* Accept the direction change command, only if POT is near minimum value*/
            if(PotValue < ((uint16_t)(MAX_ADC_COUNT)) >> 2)
            {
                /* Changing motor direction: 0 Forward, 1 Reverse*/
                if(motorDirection == 0) motorDirection = 1;
                else if(motorDirection == 1) motorDirection = 0;
            }
        }

        if (SysTick_IsTimeoutReached(&led_timeout))
        {
            SysTick_ResetTimeOut(&led_timeout);
            LED1_Toggle();
        }
    }

    return (0);
}


void ADC2_ChannelCallback (enum ADC2_CHANNEL channel, uint16_t adcVal)
{
    if(channel != ADC2_POT) return;

    /* Read Inputs */
    HallValue = (0x0007 &((HALL_A_GetValue()<<2) + (HALL_B_GetValue()<<1) + HALL_C_GetValue()));

    Ia = (float)(ADC1_ConversionResultGet(ADC1_IA) * ADC_CURRENT_SCALE);
    Ib = (float)(ADC2_ConversionResultGet(ADC2_IB) * ADC_CURRENT_SCALE);
    Ic = (float)(ADC3_ConversionResultGet(ADC3_IC) * ADC_CURRENT_SCALE);
    
    Ibus = (float)(ADC3_ConversionResultGet(ADC3_IBUS) * ADC_CURRENT_SCALE);
    Vbus = (float)(ADC3_ConversionResultGet(ADC3_VBUS) * ADC_VOLTAGE_SCALE);

    Va = (float)(ADC1_ConversionResultGet(ADC1_VM1) * ADC_VOLTAGE_SCALE);
    Vb = (float)(ADC1_ConversionResultGet(ADC1_VM2) * ADC_VOLTAGE_SCALE);
    Vc = (float)(ADC2_ConversionResultGet(ADC2_VM3) * ADC_VOLTAGE_SCALE);

    PotValue = ADC2_ConversionResultGet(ADC2_POT);
  
    /* Update the duty cycle according to the POT value, a POT follower is implemented here*/
    DesiredPWMDutyCycle = MIN_DUTY + (uint32_t)((PotValue * (MAX_DUTY - MIN_DUTY)) / MAX_ADC_COUNT );
    if (CurrentPWMDutyCycle != DesiredPWMDutyCycle)
    {
        if (CurrentPWMDutyCycle < DesiredPWMDutyCycle)
            CurrentPWMDutyCycle +=dutyRampValue;
        if (CurrentPWMDutyCycle > DesiredPWMDutyCycle)
            CurrentPWMDutyCycle -=dutyRampValue;
    }
    /* Limit Duty cycle */
    if (CurrentPWMDutyCycle < MIN_DUTY)
        CurrentPWMDutyCycle = MIN_DUTY;
    if (CurrentPWMDutyCycle > MAX_DUTY)
        CurrentPWMDutyCycle = MAX_DUTY;

    PG1DC = PG2DC = PG3DC = CurrentPWMDutyCycle;

    /***/
    
    /* Set Commutation Sector */
    if(RunMotorCommand)
    {
        if(motorDirection)
        {
            /* motorDirection = 1 for Reverse */
            PWM_setState(7-HallValue);
        }
        else
        {
            /* motorDirection = 0 for Forward */
            PWM_setState(HallValue);
        }
    }
    else
    {
        PWM_setState(0);
    }

    X2Cscope_Update();
}

void PWM_setState(uint16_t sector)
{
    PG1IOCON2 &= 0x00000000;
    PG2IOCON2 &= 0x00000000;
    PG3IOCON2 &= 0x00000000;

    PG1IOCON2 += PWM_STATE1[CommutationSector[7-sector]];
    PG2IOCON2 += PWM_STATE2[CommutationSector[7-sector]];
    PG3IOCON2 += PWM_STATE3[CommutationSector[7-sector]]; 
}
